### ISSUE TITLE
Paper details

### ISSUE THREAD

**Issue by Stangerine** [matteo-dunnhofer/SkiTB-toolkit#1]
Hello author, do you provide the code of the $STARK_{ski}$ model in the paper?

**Comment by matteo-dunnhofer** [comment]
Hi @Stangerine 

raw code and checkpoints for STARK_ski can be downloaded from this link: https://uniudamce-my.sharepoint.com/:f:/g/personal/matteo_dunnhofer_uniud_it/ElPq4Jp6OdVKqS-nxzLpWCgBYZEPg8YRSV6ZbbUlSIy8Ng?e=hhmvJ5

**Comment by Stangerine** [comment]
Thanks.

**Comment by Stangerine** [comment]
Hello author, the difference between the two instances of $STARK$, $STARK_{FT-SC}$ and $STARK_{FT}$, is the difference in search area factor? The training data are all based on multi-camera data.

**Comment by matteo-dunnhofer** [comment]
Yes, the only difference is the searching factor. Both instances are fine-tuned with the same training splits and sampling mechanism.

**Comment by Stangerine** [comment]
Thank you. Did you use other datasets, such as LaSOT, during training? Did you first train on the dataset in the below picture? Then fine-tune on the SkiTB dataset?
![image](https://github.com/user-attachments/assets/16595bfa-bc58-47a7-a85e-95c40f582d42)

**Comment by matteo-dunnhofer** [comment]
No, just used the SkiTB's training set to fine-tune starting from the checkpoint originally provided by the STARK's authors.

**Comment by Stangerine** [comment]
ok，thanks
